spring.application.name=LearningRESTAPis

spring.datasource.url=jdbc:mysql://localhost:3306/WebSecurity_db
spring.datasource.username=root
spring.datasource.password=daya1234@Daya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.security.user.name=daya
#spring.security.user.password=daya

jwt.secretKey = nmsodfgsdofgsdyftgwefg-wertyerergadvadfg

server.port=9000