spring.application.name=LearningRESTAPis
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/dayan/OneDrive/Documents/Tutorials/SpringBootFile/db
spring.datasource.username=daya
spring.datasource.password=Daya123
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.path=/h2-console